services:
  frontend:
    build:
      context: ./frontend
    restart: always
    environment:
      - EXAMCREATE_FRONTEND_HOST="localhost"
      - EXAMCREATE_BACKEND_URL="http://backend:3000"
      - EXAMCREATE_STATSERVICE_URL="http://statservice:8000"
    ports:
      - "80:80"
    networks:
      - examcreate-network
    depends_on:
      - backend
      - statservice

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - examcreate-network

  statservice:
    build:
      context: ./statService
    restart: always
    environment:
      - EXAMMANAGE_BACKEND_URL=http://exammanage-backend:8080
    ports:
      - "8000:8000"
    networks:
      - examcreate-network
      - exammanage-back-tier

networks:
  examcreate-network:
    driver: bridge
  exammanage-back-tier:
    external: true
